spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kb
    username: kbuser
    password: kbpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
