spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kb
    username: kbuser
    password: kbpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  graphql:
    path: /graphql

server:
  port: 8080
